### ISSUE TITLE
Requirement in engines/node incorrect

### ISSUE THREAD

**Issue by ace130-github** [r-murphy/openui5-preload#8]
As of version 2.3.2, the required node engine version is specified as **>=6** in `package.json`.
But it does not work with node version **<10** because of the dependencies' requirements.

The obvious solution would be to specify
```
  "engines": {
    "node": ">= 10"
  },
```

However, since with HANA XSA before SPS04, only node v.8 was supported, it may be useful to support node v.8 as well. This can be done by downgrading some of the dependencies. I have created a pull request to that effect.

**Comment by r-murphy** [comment]
Hi @ace130-github . Thanks for the PR. I've published it in version 3.2.0.

Ryan

**Comment by ace130-github** [comment]
Wow that was fast! Thank you :+1:
